### PR TITLE
Download JVM dependent jfx binaries

### LINKED ISSUE #238: Font issue on Big Sur
**Describe the bug**

Font garbled on MacOS Big Sur (probably MacOS Catalina too).

**To Reproduce**

```
$ java --version
openjdk 11.0.8 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+11)
OpenJDK 64-Bit Server VM (build 11.0.8+11, mixed mode)
```
```
$ java -jar recaf-2.4.1-J8-jar-with-dependencies.jar
```
**Exception**
```
13:46:04.488 [main] INFO : Missing JavaFX dependencies, attempting to patch in missing classes
13:46:04.490 [main] INFO :  - Local cache found!
13:46:04.491 [main] INFO :  - Loading dependencies...
13:46:04.509 [main] INFO :  - Done!
13:46:04.509 [main] INFO : Recaf-2.4.1
2020-08-14 13:46:05.654 java[24770:368934] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-08-14 13:46:05.654 java[24770:368934] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2020-08-14 13:46:05.660 java[24770:368934] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
13:46:05.745 [main] INFO : Loaded workspace from: ReaderSDK-impl-en_GB.jar
2020-08-14 13:46:05.939 java[24770:368934] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-08-14 13:46:06.013 java[24770:368984] CoreText note: Client requested name ".SFNS-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
...etc...
```

**Screenshots**
image

### PR DESCRIPTION
**Pull request by xxDark**
## What's fixed

#238

### CODE REVIEW

**Comment by xxDark** [comment]
I'm not sure if dependencies actually depend on JVM version, can we just download latest ones?
@Col-E

File: src/main/java/me/coley/recaf/util/self/SelfDependencyPatcher.java [hunk 1]
```diff
@@ -29,10 +29,10 @@
...
 	private static final Path DEPENDENCIES_DIR_PATH = Recaf.getDirectory("dependencies");
 	private static final String[] DEPENDENCIES = new String[] {
-		"https://repo1.maven.org/maven2/org/openjfx/javafx-media/11.0.2/javafx-media-11.0.2-%s.jar",
-		"https://repo1.maven.org/maven2/org/openjfx/javafx-controls/11.0.2/javafx-controls-11.0.2-%s.jar",
-		"https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/11.0.2/javafx-graphics-11.0.2-%s.jar",
-		"https://repo1.maven.org/maven2/org/openjfx/javafx-base/11.0.2/javafx-base-11.0.2-%s.jar"
+		"https://repo1.maven.org/maven2/org/openjfx/javafx-media/%d.0.2/javafx-media-%d.0.2-%s.jar",
+		"https://repo1.maven.org/maven2/org/openjfx/javafx-controls/%d.0.2/javafx-controls-%d.0.2-%s.jar",
+		"https://repo1.maven.org/maven2/org/openjfx/javafx-graphics/%d.0.2/javafx-graphics-%d.0.2-%s.jar",
+		"https://repo1.maven.org/maven2/org/openjfx/javafx-base/%d.0.2/javafx-base-%d.0.2-%s.jar"
```
Comment (Col-E) [inline src/main/java/me/coley/recaf/util/self/SelfDependencyPatcher.java:35]: This works for major versions assuming the release is `X.0.0` but more work will need to be done if we want to target patch versions. Consider if a user is on JDK 15 and `15.0.0` is out but not the patch. 

I used these versions because its a fair lowest-common-denominator. JDK 11 is the version you should jump to after JDK 8 if you're being conservative. If the bytecode version of the current JVM is compatible with the latest library version there is no reason to not use a newer version of the library. I've not checked what bytecode level the newer library versions target.

My initial thoughts for doing this are:

1. Breaking this up into a series of sub-arrays with descending versions, grabbing the highest supported one.
2. Create a basic web scraper for the JavaFX maven directory and pull the latest version allowed.

**Comment by xxDark** [comment]
@Col-E

**Comment by Col-E** [comment]
Great, merging now 👌
