### PR TITLE
Fix #344 cfr inner class name replace

### LINKED ISSUE #344: StringIndexOutOfBoundsException in CfrDecompiler.clean
Upon decompiling a specific class in Recaf 2.17.3 with CFR, the Recaf CFR decompiler _integration_ (not the decompiler itself) runs into "java.lang.StringIndexOutOfBoundsException"

**To Reproduce**

* Download the JAR for https://mvnrepository.com/artifact/com.google.code.gson/gson/2.2.4 (https://repo1.maven.org/maven2/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar)
* File -> Load -> gson-2.2.4.jar
* Decompile class "com/google/gson/internal/$Gson$Types$GenericArrayTypeImpl"

//exp: decompiles successfully
//act: java.lang.StringIndexOutOfBoundsException

**Exception**

From console output:
```
08:38:40.837 [pool-6-thread-3] ERROR: Class failed to decompiled: com/google/gson/internal/$Gson$Types$GenericArrayTypeImpl
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at me.coley.recaf.decompile.cfr.CfrDecompiler.clean(CfrDecompiler.java:93)
        at me.coley.recaf.decompile.cfr.CfrDecompiler.decompile(CfrDecompiler.java:64)
        at me.coley.plugin.decompile.DecompilePanel.lambda$startDecompile$2(DecompilePanel.java:78)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
i.e. the crash is not in CFR (which I validated to decompile), but in the integration of CFR at https://github.com/Col-E/Recaf/blob/master/src/main/java/me/coley/recaf/decompile/cfr/CfrDecompiler.java#L93

### PR DESCRIPTION
**Pull request by TimmyOVO**
## What's new
 NONE
* Summary of additions

## What's fixed

* Summary of bugs fixed
* #344

### CODE REVIEW

File: src/main/java/me/coley/recaf/decompile/cfr/CfrDecompiler.java [hunk 1]
```diff
@@ -87,8 +92,13 @@ private String clean(String decompilation, String name) {
 		// Fix inner class names being busted, "Outer.1" instead of "Outer$1"
 		String simple = name.contains("/") ? name.substring(name.lastIndexOf('/') + 1) : name;
 		if(simple.contains("$")) {
-			// They have "." instead of "$"
-			decompilation = decompilation.replace(simple.replace("$", "."), simple);
+			// They will replace last of "$" with "."
+			decompilation = decompilation.replace(
+					new StringBuilder(simple).replace(
+							simple.lastIndexOf("$"), simple.lastIndexOf("$") + 1, "."
+					).toString(),
```
Comment (Col-E) [inline src/main/java/me/coley/recaf/decompile/cfr/CfrDecompiler.java:99]: Is there a reason why this needs to be wrapped in a `StringBuilder`?

**Review by Col-E — CHANGES_REQUESTED** [review]

File: src/main/java/me/coley/recaf/decompile/cfr/CfrDecompiler.java (hunk 1 above)
Comment (TimmyOVO) [reply src/main/java/me/coley/recaf/decompile/cfr/CfrDecompiler.java:99]: Only need to replace the last "$" with "."
